// src/core/config.ts
import { existsSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

export const STARTER_CONFIG = `{
  // Starter config generated by markdownlint plugin
  "default": true,

  // Relaxed rules for practical use
  "MD013": false,           // Line length - often impractical
  "MD033": false,           // Inline HTML - needed for badges, details, etc.
  "MD041": false,           // First line h1 - not always wanted

  // Keep these strict (catch real issues)
  "MD001": true,            // Heading increment (no skipping h1 to h3)
  "MD012": { "maximum": 1 },// Multiple blank lines
  "MD022": true,            // Headings need blank lines
  "MD031": true,            // Fenced code needs blank lines
  "MD047": true             // File should end with newline
}
`;

const CONFIG_NAMES = [
  '.markdownlint.jsonc',
  '.markdownlint.json',
  '.markdownlint.yaml',
  '.markdownlint.yml',
  '.markdownlint-cli2.jsonc',
  '.markdownlint-cli2.json',
];

export async function findExistingConfig(
  directory: string
): Promise<string | null> {
  for (const name of CONFIG_NAMES) {
    const path = join(directory, name);
    if (existsSync(path)) {
      return path;
    }
  }
  return null;
}

export interface InitConfigResult {
  created: boolean;
  path: string;
  existingPath?: string;
}

export async function initConfig(directory: string): Promise<InitConfigResult> {
  const existing = await findExistingConfig(directory);

  if (existing) {
    return {
      created: false,
      path: existing,
      existingPath: existing,
    };
  }

  const newPath = join(directory, '.markdownlint.jsonc');
  writeFileSync(newPath, STARTER_CONFIG, 'utf-8');

  return {
    created: true,
    path: newPath,
  };
}
